"""bug fix

Revision ID: 2d82e0efa006
Revises: 2f89e67f64c7
Create Date: 2021-02-09 02:49:42.089049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d82e0efa006'
down_revision = '2f89e67f64c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_card_number', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.drop_column('transactions', 'paid_for')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('paid_for', mysql.ENUM('RIDE', 'TOPUP'), nullable=True))
    op.drop_table('top_up')
    # ### end Alembic commands ###
