"""test nav

Revision ID: 378521ce3a86
Revises: b906a6fdcce3
Create Date: 2021-01-26 14:28:37.822920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378521ce3a86'
down_revision = 'b906a6fdcce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sessionVar', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessionVar')
    # ### end Alembic commands ###
