"""first migration

Revision ID: a6049716d7a6
Revises: 
Create Date: 2021-01-25 13:08:39.131715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6049716d7a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_number', sa.Integer(), nullable=True),
    sa.Column('bike_pin', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('YES', 'NO', name='bikestatus'), nullable=True),
    sa.Column('last_location', sa.Enum('HILLHEAD', 'PARTICK', 'FINNIESTON', 'GOVAN', 'LAURIESTON', name='locationnames'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_info_bike_number'), 'bike_info', ['bike_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('city', sa.Enum('GLASGOW', name='cityname'), nullable=True),
    sa.Column('user_type', sa.Enum('NORMAL', 'OPERATOR', 'MANAGER', name='usertype'), nullable=True),
    sa.Column('wallet', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('current_rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bike_number', sa.Integer(), nullable=False),
    sa.Column('start_location', sa.Enum('HILLHEAD', 'PARTICK', 'FINNIESTON', 'GOVAN', 'LAURIESTON', name='locationnames'), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bike_number'], ['bike_info.bike_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Enum('NORMAL', 'OPERATOR', 'MANAGER', name='usertype'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ride_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bike_number', sa.Integer(), nullable=False),
    sa.Column('start_location', sa.Enum('HILLHEAD', 'PARTICK', 'FINNIESTON', 'GOVAN', 'LAURIESTON', name='locationnames'), nullable=True),
    sa.Column('end_location', sa.Enum('HILLHEAD', 'PARTICK', 'FINNIESTON', 'GOVAN', 'LAURIESTON', name='locationnames'), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bike_number'], ['bike_info.bike_number'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['current_rides.ride_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('CARD', 'WALLET', name='paymenttype'), nullable=True),
    sa.Column('credit_card_number', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('ride_id', sa.String(length=64), nullable=True),
    sa.Column('paid', sa.Enum('YES', 'NO', name='paidstatus'), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['current_rides.ride_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('ride_log')
    op.drop_table('login_logs')
    op.drop_table('current_rides')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bike_info_bike_number'), table_name='bike_info')
    op.drop_table('bike_info')
    # ### end Alembic commands ###
